export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const RESET = "RESET";
export const CUSTDETAILSUPDATE="CUSTDETAILSUPDATE";
export const CUSTGRPDETAILSUPDATE="CUSTGRPDETAILSUPDATE";
export const PROFDTLS="PROFDTLS";
export const RECACTDTLS="RECACTDTLS";
export const PNDINVLIST="PNDINVLIST";



